### ISSUE TITLE
borrow-bag requires rebuild even if nothing has changed

### ISSUE THREAD

**Issue by coder543** [gotham-rs/gotham#18]
cross-posting this bug here: https://github.com/smangelsdorf/borrow-bag/issues/1

Currently, any crate that depends on borrow-bag must be rebuilt every time. In practice, this means "cargo build" on `example-app` will trigger a rebuild of borrow-bag, then a rebuild of gotham, then a rebuild of `example-app`, even if nothing has changed. This makes it annoying to run `example-app` multiple times in short order, because it takes a solid 11 seconds to rebuild `example-app` on my high-end laptop, even though nothing has changed.

**Comment by smangelsdorf** [comment]
This is fixed by https://github.com/gotham-rs/borrow-bag/pull/2 (which is released in the `borrow-bag` 0.3.1 crate).

This version already satisfies the Gotham dependency on borrow-bag 0.3, but `Cargo.lock` will need to be updated locally for anyone encountering this bug.

**Comment by bradleybeddoes** [comment]
An example proving that all is now well:

```
$ cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating borrow-bag v0.3.0 -> v0.3.1

$ cargo run
 Downloading borrow-bag v0.3.1
   Compiling borrow-bag v0.3.1
   Compiling gotham v0.1.0
   Compiling hello_world v0.1.0 (file:///Users/bradleybeddoes/Development/gotham-rs/hello-world)
    Finished dev [unoptimized + debuginfo] target(s) in 8.39 secs
    Running `target/debug/hello_world`
Listening on http://127.0.0.1:7878
^C

$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/hello_world`
Listening on http://127.0.0.1:7878
```

🎉

**Comment by pftbest** [comment]
I still have this issue, every time I do `cargo run` i se this:
```
$ cargo run
   Compiling borrow-bag v0.3.1
   Compiling gotham v0.1.1
   Compiling main_service v0.1.0 (file:///home/user/Projects/ctf/tgrab/main_service)
    Finished dev [unoptimized + debuginfo] target(s) in 11.16 secs
     Running `target/debug/main_service`
```

**Comment by bradleybeddoes** [comment]
@pftbest that is quite strange, this certainly fixed the issue for me and others here.

What combination of Rust and operation system are you working with?

**Comment by pftbest** [comment]
It happens both on my Linux machine and on my MacBook with case-sensitive macOS.

Maybe case sensitivity of a filesystem plays a role here.

**Comment by bradleybeddoes** [comment]
Have confirmed on Gotham Gitter channel that this has come back for folks that is was solved for, working theory being a recent change to skeptic.

**Comment by smangelsdorf** [comment]
This is fixed (correctly this time) by https://github.com/gotham-rs/borrow-bag/pull/7, which is released in the `borrow-bag` 0.3.2 crate.
